#sudo: required

env:
   global:
   - PATH=$PATH:$TRAVIS_BUILD_DIR/google-cloud-sdk/bin
   - GCE_PROJECT_ID="openshift-descheduler-infra"
   - GCE_ZONE="us-east1-b"
   - GCE_SA_CREDS="$PWD/client.json"

before_install:
- sudo apt-get install -y uuid
- openssl aes-256-cbc -K $encrypted_3a6a9b488437_key -iv $encrypted_3a6a9b488437_iv -in client.json.enc -out client.json -d

script:
- hack/e2e_gce/install_gcloud.sh
- hack/e2e_gce/gcloud_sdk_configure.sh
- hack/e2e_gce/gcloud_create_cluster.sh 
- hack/e2e_gce/delete_cluster.sh #This will be created as part of gcloud_create_cluster.sh

